/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_android_wifi_tether_system_NativeTask */

#ifndef com_tdhite_dnsqache_system_NativeTask_H
#define com_tdhite_dnsqache_system_NativeTask_H
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_com_tdhite_dnsqache_system_NativeTask
 * Method:    getProp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tdhite_dnsqache_system_NativeTask_getProp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_com_tdhite_dnsqache_system_NativeTask
 * Method:    runCommand
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tdhite_dnsqache_system_NativeTask_runCommand
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
